apiVersion: v1
kind: Secret
metadata:
  name: kafka-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "product-management.labels" . | nindent 4 }}
type: Opaque
stringData:
  kafka-user: {{ .Values.secrets.kafkaUser | quote }}
  kafka-password: {{ .Values.secrets.kafkaPassword | quote }}
  KAFKA_SASL_JAAS_CONFIG: {{ printf "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"%s\" password=\"%s\";" .Values.secrets.kafkaUser .Values.secrets.kafkaPassword | quote }}
