overrides:
  '@babel/core@<=7.29.0': '>=7.29.6'
  esbuild@<=0.24.2: '>=0.25.0'
  react-router@>=6.7.0 <6.30.4: '>=6.30.4'
  vite@<=6.4.1: '>=6.4.2'
  vite@<=6.4.2: '>=6.4.3'
  vitest@<3.2.6: '>=3.2.6'
